name: Test
on:
  - push

jobs:
  build:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Cabal
        run: sudo apt-get update && sudo apt-get install cabal-install

      - name: cabal build
        run: cabal build

      - name: cabal test
        run: cabal test